2025-06-16 12:13:37,929 - __main__ - INFO - Starting BrotBot server...
2025-06-16 12:13:40,232 - __main__ - INFO - Starting BrotBot server...
2025-06-16 12:37:58,096 - __main__ - INFO - Starting BrotBot server...
2025-06-17 12:55:49,450 - __main__ - INFO - Starting BrotBot server...
2025-06-17 12:55:50,504 - __main__ - INFO - Starting BrotBot server...
2025-06-17 12:56:26,192 - __main__ - INFO - Starting BrotBot server...
2025-06-17 12:56:27,285 - __main__ - INFO - Starting BrotBot server...
2025-06-17 12:58:42,549 - __main__ - INFO - Starting BrotBot server...
2025-06-17 12:58:43,603 - __main__ - INFO - Starting BrotBot server...
2025-06-17 12:59:02,360 - app.handlers.order.order_commands - ERROR - Unexpected error in handle_add_order: (pymysql.err.OperationalError) (1054, "Unknown column 'users.is_admin' in 'field list'")
[SQL: SELECT users.user_id AS users_user_id, users.slack_id AS users_slack_id, users.name AS users_name, users.is_away AS users_is_away, users.is_admin AS users_is_admin 
FROM users 
WHERE users.slack_id = %(slack_id_1)s 
 LIMIT %(param_1)s]
[parameters: {'slack_id_1': 'U08LZK84FFZ', 'param_1': 1}]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-06-20 09:44:02,957 - __main__ - INFO - Starting BrotBot server...
2025-06-20 09:44:04,056 - __main__ - INFO - Starting BrotBot server...
2025-06-20 09:51:24,929 - __main__ - INFO - Starting BrotBot server...
2025-06-20 09:51:26,002 - __main__ - INFO - Starting BrotBot server...
2025-06-20 09:53:27,486 - app.handlers.order.order_commands - ERROR - Unexpected error in handle_add_order: (pymysql.err.OperationalError) (1054, "Unknown column 'users.is_admin' in 'field list'")
[SQL: SELECT users.user_id AS users_user_id, users.slack_id AS users_slack_id, users.name AS users_name, users.is_away AS users_is_away, users.is_admin AS users_is_admin 
FROM users 
WHERE users.slack_id = %(slack_id_1)s 
 LIMIT %(param_1)s]
[parameters: {'slack_id_1': 'U08LZK84FFZ', 'param_1': 1}]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-06-20 09:53:37,395 - app.handlers.order.order_commands - ERROR - Unexpected error in handle_add_order: (pymysql.err.OperationalError) (1054, "Unknown column 'users.is_admin' in 'field list'")
[SQL: SELECT users.user_id AS users_user_id, users.slack_id AS users_slack_id, users.name AS users_name, users.is_away AS users_is_away, users.is_admin AS users_is_admin 
FROM users 
WHERE users.slack_id = %(slack_id_1)s 
 LIMIT %(param_1)s]
[parameters: {'slack_id_1': 'U08LZK84FFZ', 'param_1': 1}]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-06-20 10:06:25,899 - app.handlers.order.order_commands - ERROR - Unexpected error in handle_add_order: Instance '<Order at 0x1da5eefbcb0>' is not persistent within this Session
2025-06-20 10:20:11,364 - __main__ - INFO - Starting BrotBot server...
2025-06-20 10:20:12,425 - __main__ - INFO - Starting BrotBot server...
2025-06-20 10:20:24,692 - app.handlers.order.order_commands - ERROR - Unexpected error in handle_add_order: Instance '<Order at 0x1bdaf224ec0>' is not persistent within this Session
2025-06-20 10:31:37,152 - __main__ - INFO - Starting BrotBot server...
2025-06-20 10:31:39,718 - __main__ - INFO - Starting BrotBot server...
2025-06-20 11:34:11,311 - __main__ - INFO - Starting BrotBot server...
2025-06-20 11:34:12,493 - __main__ - INFO - Starting BrotBot server...
2025-06-20 12:08:46,530 - __main__ - INFO - Starting BrotBot server...
2025-06-20 12:08:48,078 - __main__ - INFO - Starting BrotBot server...
2025-06-20 12:11:39,321 - __main__ - INFO - Starting BrotBot server...
2025-06-20 12:11:41,506 - __main__ - INFO - Starting BrotBot server...
2025-06-20 12:16:01,140 - __main__ - INFO - Starting BrotBot server...
2025-06-20 12:16:02,288 - __main__ - INFO - Starting BrotBot server...
2025-06-20 12:59:48,312 - __main__ - INFO - Starting BrotBot server...
2025-06-20 12:59:49,909 - __main__ - INFO - Starting BrotBot server...
